/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Boost '2', '3' and '4'.": "提升 '2', '3' 和 '4'.",
    "Currently:": "当前:",
    "Gain more numbers based on points.": "基于点数获得更多数字。",
    "Gain more points based on numbers.": "基于数字获得更多点数。",
    "Guide": "指南",
    "Link": "链接",
    "My server": "我的服务器",
    "Numbers": "数字",
    "Points boost itself.": "点数提升它自己。",
    "Quadruple point gain.": "四倍点数增益。",
    "Time": "时间",
    "Automation": "自动化",
    "Base++": "基础++",
    "Buyable challenge!": "可购买的挑战！",
    "Buyable challenge?": "可购买的挑战？",
    "Challenged": "挑战",
    "complete / factor. Reward: Number x2.": "完整/因子。奖励：数字x2。",
    "Complete Buyable upgrader once.": "完成一次可购买升级器。",
    "Complete Buyable upgrader three times.": "完成 3 次可购买升级器。",
    "Complete Super 3 in 1": "完成超级 3 合 1",
    "Factor": "因子",
    "Factors": "因子",
    "First": "第一滴血",
    "Get 1 Infinity.": "获得 1 无限。",
    "Get the first upgrade, reward: point x1.25": "获得第一次升级，奖励：点x1.25",
    "Get the fourth upgrade, reward: Number x3.": "获得第四次升级，奖励：数字x3。",
    "Inflatity": "通货膨胀",
    "More and more": "越来越多",
    "Multiply IP gain by 1e15.": "将 IP 增益乘以 1e15。",
    "Next layer at 5 Number upgrade": "下一层在 5 号升级",
    "one to fifteen": "一到十五",
    "Raise O gain to 1.5.": "将 O 增益提高到 1.5。",
    "Remove the first hardcap of '+', auto buy Factors, and Factors resets nothing.": "删除“+”的第一个硬上限，自动购买因子，因子不会重置任何内容。",
    "Remove the second hardcap of '+'.": "删除“+”的第二个硬上限。",
    "Save bank": "存档银行",
    "Super Challenged": "超级挑战",
    "Super click": "超级点击",
    "Ten Upgrade": "十次升级",
    "The first Factor milestone is better.": "第一个因子里程碑更好。",
    "Unlock a new upgrade and Factors boost number and point gain.": "解锁新的升级和因子提升数量和点数增益。",
    "Unlock a number buyable.": "解锁可购买的数字。",
    "Unlock another Factor challenge": "解锁另一个因子挑战",
    "Unlock another Factor challenge and double number gain.": "解锁另一个因子挑战和双倍数量增益。",
    "Unlock another number upgrade": "解锁另一个数字升级",
    "Unlock another number upgrade.": "解锁另一个数字升级。",
    "Unlock another Number upgrade.": "解锁另一个数字升级。",
    "Unlock Factor upgrades and gain 100% of numbers on reset per second": "解锁因子升级并在每秒重置时获得 100% 的数字",
    "Unlock the first Factor challenge": "解锁第一个因子挑战",
    "~2^10 factor": "~2^10 因子",
    "Show guide": "显示指南",
    "'Factor Alpha' is better": "“因子Alpha”更好",
    "'Factor Alpha' is much better.": "“因子Alpha”要好得多。",
    "'Factor Beta' is better.": "“因子Beta”更好。",
    "Remove the first hardcap of '2' and '4'.": "删除“2”和“4”的第一个硬上限。",
    "Goal:": "目标:",
    "Reward:": "奖励:",
    "/ factor": "/ 因子",
    "Challenges": "挑战",
    "There are upgrades that require being in a challenge (Number Upgrade).": "有些升级需要挑战（数字升级）。",
    "Remove the second hardcap of '2' but nerf it.": "移除“2”的第2个硬上限，但削弱它。",
    "Boost point and number gain based on Factors.": "提升点和数量增益基于因子。",
    "Factor Alpha": "因子 Alpha",
    "Factor Beta": "因子 Beta",
    "Numbers boost itself.": "数字提升它自己。",
    "Upgrades": "升级",
    "Factor Delta": "因子 Delta",
    "Factor Gamma": "因子 Gamma",
    "Factor Iota": "因子 Iota",
    "Factor Kappa": "因子 Kappa",
    "Factor milestone 4 and upgrades are useless.": "因子里程碑 4 和升级是无用的。",
    "Factor Theta": "因子 Theta",
    "Factor will not reset upgrades and numbers x1.5.": "因子不会重置升级和数字 x1.5。",
    "Factor Zeta": "因子 Zeta",
    "Factors are cheaper and unlock a factor upgrade.": "因子更便宜并解锁因子升级。",
    "Free Infinity": "免费无限",
    "Get '-3'": "得到'-3'",
    "Get 1 Factor shift.": "获得 1 个因子偏移。",
    "Get 1 Infinity point.": "获得 1 个无限点。",
    "Get 1 Mathematics Symbol. Reward: Always keep factor shift milestone on reset.": "获得 1 个数学符号。 奖励：始终保持因子偏移里程碑重置。",
    "Get 1.8e258 Number in IC2, reward: Number x1e50 in Row 1, 3 Infinity Challenge.": "IC2中获得1.8e258数字，奖励：第1行数字x1e50，3无限挑战。",
    "Get 1.8e308 point.": "获得 1.8e308 点。",
    "Get 18 Number Upgrade, reward: Number x5.": "获得18数字升级，奖励：数字x5。",
    "Get 1e25000 Number in IC3. Reward: Unlock 1 Infinity challenge.": "在 IC3 中获取 1e25000 数字。 奖励：解锁 1 个无限挑战。",
    "Get 1e50 Negative numbers in IC5, reward: Unlock 1 Number buyable.": "在IC5中获得1e50个负数，奖励：解锁1个可购买的数字。",
    "Get 23 Factor Upgrade. Reward: Number x1e5": "获得 23 因子升级。 奖励：数字x1e5",
    "'+' work in 'Buyable Upgrader' but nerf it in 'Buyable Upgrader'": "“+”在“可购买升级器”中有效，但在“可购买升级器”中削弱它",
    "'2' is useless": "'2' 没用",
    "'6', '7' and '8' are useless.": "'6'、'7' 和 '8' 没用。",
    "Buyables": "可购买",
    "Boost 'Factor Beta' and unlock 1 more factor upgrade.": "提升“因子 Beta”并解锁 1 个因子升级。",
    "No cap factor": "无上限因子",
    "No factor factor": "无因子因子",
    "No upgrade factor": "无升级因子",
    "Points and Numbers x2": "点数和数字 x2",
    "Remove the first hardcap of '3'.": "删除“3”的第一个硬上限。",
    "Remove the fourth hardcap of '2'.": "移除“2”的第四个硬上限。",
    "Remove the second hardcap of '3'": "删除“3”的第二个硬上限",
    "Remove the second hardcap of '4'.You can buy this upgrade while you are in Factor Challenge 5.": "移除“4”的第二个硬上限。您可以在因子挑战 5 中购买此升级。",
    "Remove the third hardcap of '2'. You can buy this upgrade while you are in Factor Challenge 4.": "移除“2”的第三个硬上限。 您可以在因子挑战 4 中购买此升级。",
    "Unlock 1 factor challenge": "解锁 1 因子挑战",
    "Unlock 2 factor challenges.": "解锁 2 个因子的挑战。",
    "Unlock 2 Number upgrades, 2 Factor challenges and you can buy max factor.": "解锁 2 个数字升级、2 个因子挑战，您可以购买最大因子。",
    "Unlock a number upgrade.": "解锁数字升级。",
    "You are trapped in / and No upgrade factor.": "你被困在 / 并且没有升级因子。",
    "You are trapped in 2 in 1, No cap and no factor factor.": "您被困在 2 合 1 中，没有上限，也没有因子因子。",
    "69 Infinity (NICE)": "69 无限 (不错)",
    "Auto buy Upgrade Factor, unlock 1 challenge and 5 upgrade.": "自动购买升级因子，解锁 1 次挑战和 5 次升级。",
    "First four Upgrade Factor Unlock 1 upgrade and point x2, keep upgrade on reset": "前四个升级因子解锁 1 升级和点 x2，重置时保持升级",
    "Infinity": "无限",
    "Infinity boost Negative Numbers gain and auto buy factor and number buyable.": "无限提升负数增益和自动购买因子和可购买数量。",
    "keep Factor challenge on reset, and '9' to '16' on ALL reset.": "在重置时保持因子挑战，在所有重置时保持“9”到“16”。",
    "keep Factor Upgrade, Negative number Upgrade and Negative number milestone on reset, Negative number x10.": "在重置    时保持因子升级、负数升级和负数里程碑，负数 x10。",
    "Number gain ^1.05 and point gain x100, keep upgrade on factor reset. Keep the seventeenth factor milestone on reset.": "数字增益 ^1.05 和点增益 x100，在因子重置时继续升级。保持第十七因子里程碑处于重置状态。",
    "Number gain ^1.05, keep Factor milestone and upgrade factor milestone on reset.": "数字增益 ^1.05，重置因子里程碑和升级因子里程碑。",
    "Remove the hardcap of 'Factor beta' but nerf it.": "移除“因子 beta”的硬上限，但削弱它。",
    "Unlock 1 buyable (not upgrade).": "解锁 1 个可购买（非升级）。",
    "Unlock 1 challenge (not upgrade) and point x10000.": "解锁 1 个挑战（非升级）并获得 x10000 点。",
    "Unlock 1 Negative number Upgrade and Negative number is cheaper again in IC.": "解锁 1 负数升级和负数在 IC 中再次更便宜。",
    "Unlock 1 Negative number Upgrade and Negative number is cheaper in IC.": "解锁 1 负数升级和负数在 IC 中更便宜。",
    "Unlock 1 upgrade.": "解锁 1 次升级。",
    "Unlock 2 Infinity challenge.": "解锁 2 无限挑战。",
    "Unlock 2 Number upgrades and boost the eighth milestone.": "解锁 2 号升级并提升第八个里程碑。",
    "Unlock more challenge.": "解锁更多挑战。",
    "Upgrade Factor": "升级因子",
    "Upgrade Factor boost point and Numbers gain.": "升级因子提升点和数字增益。",
    "Upgrade factor reset nothing.": "升级因子不会重置。",
    "You can buy max Infinity.": "您可以购买最大无限。",
    "Complete Infinity Point challenge 1": "完成无限点数挑战 1",
    "Don't forget achievements": "不要忘记成就",
    "Don't forget achievements again.": "不要再次忘记成就。",
    "Get 3 Infinity.": "获得 3 无限。",
    "Get IP upgrade 33.": "获取 IP 升级 33。",
    "I find the miss one!": "我找到了小姐！",
    "I forget achievements": "我忘记了成就",
    "Impossible?": "不可能的？",
    "Nine egg": "九个蛋",
    "Omega Cheaper": "Omega更便宜",
    "Omega Upgrade": "Omega升级",
    "Second infinity": "第二无限大",
    "True Infinity": "真无限",
    "twofinity challenge": "双无限挑战",
    "A new game": "新游戏",
    "Complete a Infinity challenge with 1 ???.": "用 1 ??? 完成一个无限挑战。",
    "Complete NNC4.": "完成 NNC4。",
    "Complete NNC6.": "完成 NNC6。",
    "Do ω once.": "做一次ω。",
    "Feature Factor": "特征因子",
    "Five 1": "五 1",
    "Get 1 ???.": "得到 1 ？？？",
    "Get 1 Eternity point.": "获得 1 永恒点数。",
    "Get 1 Infinity with 1 ???.": "用 1 获得 1 无限大 ???。",
    "Get 1 Mathematician.": "获得 1 名数学家。",
    "Get 1 Ordinal  Mathematician.": "获得 1 名序数数学家。",
    "Get 1 Ordinal.": "获得 1 个序数。",
    "Get 1 prestige point.": "获得 1 点声望。",
    "Get 1 shapes.": "得到 1 个形状。",
    "Get 1 super prestige point.": "获得 1 个超级声望点。",
    "Get 1 upgrade factor with 1 ???.": "获得 1 升级因子 1 ???。",
    "Get 1 zero": "得到 1 个零",
    "get Both": "两者兼得",
    "Get e11111 IP, reward: IP gain ^1.05 and x 1e40": "获得e11111 IP，奖励：IP增益^1.05和x 1e40",
    "Get the '-' upgrade in UF layer.": "在 UF 层中获取“-”升级。",
    "Infinity time": "无限时间",
    "Infinity X": "无限 X",
    "Infinityal": "无限的",
    "Make game speed >1.": "使游戏速度>1。",
    "Mathematician": "数学家",
    "Negative help us": "负面帮助我们",
    "New things": "新事物",
    "Non upgraded upgrade factor": "非升级升级因子",
    "OM rewritten": "OM重写",
    "Over Cheaper": "便宜多了",
    "Reach 1 Factor Shift with 1 ???.": "使用 1 ??? 达到 1 个因子偏移。",
    "Reach 1.8e308 points with 1 ???. Reward: Unlock '-3' earlier": "达到 1.8e308 点 1 ???。 奖励：提前解锁'-3'",
    "Speed": "速度",
    "The first layer": "第一层",
    "The greatest shapes": "最伟大的形状",
    "The sixth row layer": "第六排层",
    "Tickspeed from AD": "来自 AD 的滴答速度",
    "True OM": "真正的OM",
    "Unlock tickspeed.": "解锁滴答速度。",
    "ω boost": "ω 提升",
    "Your point and number gain ^^0.95 and ^0.95 but every ??? will rewrite the tree .": "您的点数和数字会增加 ^^0.95 和 ^0.95 但每 ??? 将重写树。",
    "Super / factor": "超/因子",
    "Super No upgrade factor": "超级无升级因子",
    "unlock a Number buyable.": "解锁可购买的数字。",
    "Upgrade challenge": "升级挑战",
    "Buyable upgrader": "可购买升级器",
    "challenges": "挑战",
    "Factor point": "因子点",
    "Info": "信息",
    "Normal challenge": "普通挑战",
    "Points and Numbers / 1e6": "点数/1e6",
    "Points and Numbers x2 and unlock a buyable.": "点数和数字 x2 并解锁一个可购买。",
    "'-' base x2 and unlock a factor upgrade": "'-' 基数 x2 并解锁因子升级",
    "'-' have no effect and nerf '+'": "'-' 没有效果和 削弱 '+'",
    "'-' work in 'Buyable Upgrader' but nerf it in 'Buyable Upgrader'": "'-' 在'可购买升级器' 中工作，但在'可购买升级器' 中削弱它",
    "'+' is better' (1-3) and Remove 1 hardcap of '-'  (4).": "'+' 更好' (1-3) 和删除 '-' (4) 的 1 个硬上限。",
    "'2','3' and '4' ard useless.": "'2'、'3' 和 '4' 没有用。",
    "3 and unlock a upgrade.": "3、解锁升级。",
    "Auto buy Upgrade Factor.": "自动购买升级因子。",
    "Boost '+', auto buy Factors, and Factors resets nothing": "提升“+”，自动购买因子，因子不会重置任何内容",
    "Boost '11' and '11' also boost point gain. Upgrade factor boost factor point gain.": "提升“11”和“11”也提升点增益。升级因子提升因子点增益。",
    "Boost '3'. You can buy this upgrade while you are in Factor Challenge 4.": "提升“3”。您可以在因子挑战 4 中购买此升级。",
    "Boost '5' and keep all number upgrade on reset. You can buy this upgrade while you are in Factor Challenge 1.": "提升“5”并在重置时保持所有数字升级。您可以在因子挑战 1 中购买此升级。",
    "Boost 'Factor alpha' and it also affect Factor Point gain.": "提升“因子 alpha”，它也会影响因子点增益。",
    "Boost negative numbers gain by 1.00x": "将负数增益提高 1.00 倍",
    "Boost the eighth milestone.": "推进第八个里程碑。",
    "Factor booster": "因子助推器",
    "Factor Generator": "因子生成器",
    "Factor point boost number gain.": "因子点提升数字增益。",
    "Increase '/' effect base by 0.005 and unlock an upgrade.": "将“/”效果基数增加 0.005 并解锁升级。",
    "Number boost Factor point gain.": "数字提升因子点增益。",
    "Remove the first hardcap of '2' but nerf it.": "移除“2”的第一个硬上限，但削弱它。",
    "Unlock 2 more Number upgrades.": "解锁另外 2 个数字升级。",
    "Unlock 3 Infinity challenge.": "解锁 3 无限挑战。",
    "Unlock a challenge, you can buy max factor.": "解锁挑战，您可以购买最大因子。",
    "Unlock a challenge.": "解锁挑战。",
    "Unlock a number buyable and auto buy it.": "解锁可购买的数字并自动购买。",
    "Unlock another Factor challenge and multiply point gain by 100.": "解锁另一个因子挑战并将积分增益乘以 100。",
    "Unlock factor point. multiply number gain by 2.5.": "解锁因子点。将数字增益乘以 2.5。",
    "'-' base x2 and unlock a factor challenge": "'-' 基数 x2 并解锁一个因子挑战",
    "'+' and '-' have no effect": "'+' 和 '-' 无效果",
    "Factor Epsilon": "因子ε",
    "Factor Eta": "因子Eta",
    "Next layer at 1.8e308 Numbers.": "下一层在 1.8e308 数字。",
    "Super 2 in 1": "超级二合一",
    "Unlock a number buyable and Number x2": "解锁一个可购买的数字和数字 x2",
    "Unlock the first upgrade factor challenge.": "解锁第一个升级因子挑战。",
    "You are trapped in super / and super No upgrade factor.": "你被困在超级/超级没有升级因子。",
    "69 ω completions": "69 ω 完成",
    "again": "再次",
    "Auto buy IP upgrade. Keep E and MS milestone and NN challenge on reset.": "自动购买IP升级。在重置时保持 E 和 MS 里程碑和 NN 挑战。",
    "Boost 'Factor Lambda'": "提升“因子 Lambda”",
    "boost Factor milestone 1.": "提升因子里程碑 1。",
    "divide point will reset to 1e20 and give 1 Subtraction point if it smaller than 1.": "分割点将重置为 1e20，如果小于 1，则给出 1 个减法点。",
    "Do IP reset in this challenge to get more IP": "在这个挑战中重置 IP 以获得更多 IP",
    "Euclid": "欧几里得",
    "Factor are cheaper, Boost or nerf is boost IP instead of NN.": "因子 更便宜，提升 或 削弱 是 提升 IP 而不是 NN。",
    "Factor are cheaper.": "因子更便宜。",
    "Factor boost Negative numbers gain and unlock 1 upgrade.": "因子提升负数获得并解锁 1 次升级。",
    "Factor Chi": "因子Chi",
    "Factor is cheaper.": "因子更便宜。",
    "Factor Lambda": "因子 Lambda",
    "Factor Mu": "因子 Mu",
    "Factor Nu": "因子 Nu",
    "Factor Omega": "因子 Omega",
    "Factor Omicron": "因子 Omicron",
    "Factor Phi": "因子 Phi",
    "Factor Pi": "因子 Pi",
    "Factor Psi": "因子 Psi",
    "Factor Rho": "因子 Rho",
    "Factor shift": "因子偏移",
    "Factor shift reset nothing and per factor shift (up to 5) unlock a prime factor.": "因子移位不会重置任何内容，并且每个因子移位（最多 5 个）解锁一个主要因子。",
    "Factor Sigma": "因子 Sigma",
    "Factor Tau": "因子 Tau",
    "Factor Upsilon": "因子 Upsilon",
    "Factor Xi": "因子 Xi",
    "Game speed ^1.01. EP x1e8 and Mathematician is cheaper": "游戏速度^1.01。 EP x1e8 和 Mathematician 更便宜",
    "Keep I milestone and challenge on reset.": "在重置时保持我的里程碑和挑战。",
    "Keep IP content on reset.": "保持 IP 内容处于重置状态。",
    "Keep IP milestone on reset. Ordinal boost EP gain.": "保持 IP 里程碑复位。序数提升 EP 增益。",
    "Keep IP upgrade on reset.": "重置时保持 IP 升级。",
    "Keep IP, F, UF milestone on reset.": "保持 IP、F、UF 里程碑复位。",
    "Keep MS and UF upgrade on reset.": "重置时保持 MS 和 UF 升级。",
    "Keep Negative numbers challenge on reset.": "在重置时保持负数挑战。",
    "Keep Negative numbers, Infinity challenge, UF upgrade on reset. Unlock new UF upgrade.": "在重置时保持负数、无限挑战、UF 升级。解锁新的 UF 升级。",
    "Keep UF buyable on row 4 reset .": "在第 4 行重置时保持 UF 可购买。",
    "Keep UF upgrade on reset, auto buy buyable.": "重置时保持UF升级，自动购买可购买。",
    "Mathematics Symbol": "数学符号",
    "MP boost CP gain.": "MP 提升 CP 增益。",
    "Next layer at '1.798F308' upgrade (Just a upgrade name).": "'1.798F308' 升级的下一层（只是一个升级名称）。",
    "Number ^2 and Ordinal boost CP gain.": "Number ^2 和 Ordinal 提升 CP 增益。",
    "Number boost point gain.": "数字提升点增益。",
    "Number gain ^0.00002": "数字增益 ^0.00002",
    "Number gain ^1.14. However, remove upgrade factor layer (You can't get UF, but their challenge and upgrade won't reset.)": "数字增益 ^1.14。但是，删除升级因子层（您无法获得UF，但他们的挑战和升级不会重置。）",
    "Ordinal": "序数",
    "Remove E layer but Number ^10. Shape reset nothing.": "删除 E 层但编号 ^10。形状重置什么。",
    "Remove the third hardcap of '4'. You can buy this upgrade while you are in Factor Challenge 9.": "移除“4”的第三个硬上限。您可以在 因子挑战 9 中购买此升级。",
    "Shapes": "形状",
    "The '/' effect is always 3.08": "'/' 效果始终为 3.08",
    "The '+' effect is always 1.79e308": "'+' 效果始终为 1.79e308",
    "The 'x' effect is always 1.79e308": "'x' 效果始终为 1.79e308",
    "Tickspeed effect is better.": "滴答速度效果更好。",
    "True^2 Math": "真^2数学",
    "unlock ???.": "开锁 ？？？。",
    "Unlock 1 Negative number Upgrade": "解锁1个负数升级",
    "Unlock 1 number Upgrade": "解锁 1 个数字 升级",
    "Unlock 4 upgrade and Number ^1.1": "解锁 4 升级和编号 ^1.1",
    "Unlock a new prime factor, keep challenge point and upgrade point on reset.": "解锁一个新的主要因子，在重置时保持挑战点和升级点。",
    "Unlock Mathematics Symbol and Infinity point gain x100.": "解锁数学符号和无限点增益 x100。",
    "Unlock new Infinity challenge.": "解锁新的无限挑战。",
    "Unlock new upgrade challenge.": "解锁新的升级挑战。",
    "Unlock the third Infinity challenge": "解锁第三个无限挑战",
    "Upgrade Factors are cheaper and you can buy max it.": "升级因子更便宜，您可以购买最多。",
    "Upgrade factors are cheaper.": "升级因子更便宜。",
    "Which make Number Gain ^3,922": "这使得数字增益 ^3,922",
    "You can complete ω 1000 times.": "你可以完成 ω 1000 次。",
    "You have 0 Factors": "你有 0 个因子",
    "You have 2 layer left to unlock.": "您还有 2 层要解锁。",
    "Your have 1.65e9 Addition points.": "你有 1.65e9 加分。",
    "Your point and number gain ^^1 and ^1 but every ??? will rewrite the tree .": "您的点数和数字会增加 ^^1 和 ^1 但每个 ???将重写树。",
    "Your prime factor product is 1.00, which make you gain 1.00 prime factor point per second.": "您的素数因子生产是 1.00，这使您每秒获得 1.00 素数因子点数。",
    "1e105 prime factor point": "1e105 素数因子点数",
    "Factors are cheaper.": "因子更便宜。",
    "Master -": "掌握 -",
    "Master +": "掌握 +",
    "Remove the third hardcap of '3'. You can buy this upgrade while you are in Factor Challenge 11.": "删除“3”的第三个硬上限。 您可以在 因子挑战 11 中购买此升级。",
    "The '-' effect is always 1e50": "'-' 效果始终为 1e50",
    "The '+' effect is always 1e120": "'+' 效果始终为 1e120",
    "Unlock another buyable and a new numbers upgrade": "解锁另一个可购买和新数字升级",
    "Unlock the first factor buyable": "解锁第一个可购买因子",
    "'x' is better. You can buy this upgrade while you are in Upgrade Factor Challenge 2.": "'x' 更好。 您可以在升级因子挑战 2 中购买此升级。",
    "Cost: Infinity Negative numbers": "成本：无限负数",
    "Points boost themselves": "点数提升它自己",
    "Remove the fourth hardcap of '-2'. You can buy this upgrade while you are in Infinity Challenge 1.": "删除“-2”的第四个硬上限。您可以在无限挑战 1 中购买此升级。",
    "Remove the hardcap of Exponentiation point and prestige point gain.": "移除指数点和声望点增益的硬上限。",
    "Remove the third hardcap of '-4'. You can buy this upgrade while you are in Infinity Challenge 2.": "删除“-4”的第三个硬上限。您可以在无限挑战 2 中购买此升级。",
    "Reset for": "重置为",
    "UltraLuigi (Easter Egg 1, 2, 3 and 4)": "UltraLuigi（复活节彩蛋 1、2、3 和 4）",
    "Unlock 1 Negative numbers buyable.": "解锁 1 个可购买的负数。",
    "Unlock 1 Number Upgrade and Remove the hardcap of -2.": "解锁 1 个数字升级并移除 -2 的硬上限。",
    "Unlock a new layer.": "解锁新图层。",
    "Unlock Exponentiation prestige.": "解锁指数声望。",
    "Unlock Exponentiation.": "解锁指数。",
    "Unlock Infinity challenge 5.": "解锁无限挑战5。",
    "Unlock Negative numbers Challenge.": "解锁负数挑战。",
    "Unlock the first infinity challenge": "解锁第一个无限挑战",
    "Unlock the third factor buyable": "解锁可购买的第三个因子",
    "'-4' effect >= 1e48": "'-4' 效果 >= 1e48",
    "'+' effect is always 1e50, '-' effect is always 1e30 and '/' effect is always 1.5": "“+”效果始终为 1e50，“-”效果始终为 1e30，“/”效果始终为 1.5",
    "Boost '-2'": "提升'-2'",
    "Boost '-2' and '-4'": "提升“-2”和“-4”",
    "Boost '2', '3', '4'.": "提升“2”、“3”、“4”。",
    "Boost '9'": "提升'9'",
    "Boost Number gain by 1.00x": "将数字增益提高 1.00 倍",
    "Boost Point gain by 1.00x": "提升点增益 1.00 倍",
    "Factor a": "因子a",
    "factor are cheaper.": "因子更便宜。",
    "Factor b": "b因子",
    "Factor c": "因子 c",
    "Factor exponent is: 0.271(Factors are cheaper)": "因子指数为：0.271（因子更便宜）",
    "gain 100% of Infinity point on reset per second": "每秒重置时获得 100% 的无限点",
    "gain 100% of Negative numbers on reset per second and keep upgrade factor milestone on reset.": "每秒重置时获得 100% 的负数，并在重置时保持升级因子里程碑。",
    "Infinity point": "无限点",
    "Infinity points": "无限点",
    "IP upgrade 43 has no effect but Number gain ^3.": "IP 升级 43 没有效果，但数字增益 ^3。",
    "Keep '0' and Factor challenge on reset.": "重置时保持“0”和因子挑战。",
    "Keep factor upgrades and milestone on reset.": "在重置时保持因子升级和里程碑。",
    "Keep master +, -, x, /, '2', '3', '4' and '19' on ALL resets.": "在所有重置时保持主 +、-、x、/、“2”、“3”、“4”和“19”。",
    "Keep Negative numbers upgrades and milestone on reset.": "在重置时保持负数升级和里程碑。",
    "Negative numbers": "负数",
    "Negative numbers boost point gain.": "负数提高积分。",
    "Negative Numbers boost themselves": "负数自我提升",
    "Next at 1.00e940 Numbers": "接下来在 1.00e940 数字",
    "Next at 1.80e308 Negative numbers": "Next at 1.80e308 负数",
    "Next layer at 1.00e1800 Infinity points.": "下一层在 1.00e1800 无限点。",
    "Normal Challenges": "普通挑战",
    "Number buyable have no effect.": "可购买的数量没有影响。",
    "Per factor shift make factor cheaper.": "每个因子转移使因子更便宜。",
    "_lx5=nitro (Easter Egg 1 and 5)": "_lx5=nitro（复活节彩蛋 1 和 5）",
    "'-2' is no effect' .": "'-2' 没有效果' 。",
    "'-2', '-3' and '-4' is no effect.": "'-2'、'-3' 和 '-4' 无效。",
    "'-4' is no effect.": "'-4' 无效。",
    "'Factor Lambda' has no effect but Number gain ^1.75": "'因子 Lambda' 没有效果，但数字增益 ^1.75",
    "♾InFiIipity♾ (Easter Egg 1)": "♾InFiIipity♾（复活节彩蛋 1）",
    "Auto buy Negative numbers buyable and Infinity point boost Negative numbers gain.": "自动购买负数可购买和无限点提升负数增益。",
    "beatable (Easter Egg 3)": "可击败（复活节彩蛋 3）",
    "Boost '-4'": "提升'-4'",
    "Boost Number gain base on Infinity.": "提升数字 增益基于 无限。",
    "Boost or nerf": "增强或削弱",
    "Crabble (Easter Egg 3)": "螃蟹（复活节彩蛋 3）",
    "Elliott (Easter Egg 3 and 4)": "艾略特（复活节彩蛋 3 和 4）",
    "Elund (Easter Egg 1, 2 and 3)": "Elund（复活节彩蛋 1、2 和 3）",
    "Eternity 1": "永恒 1",
    "Eternity 2": "永恒 2",
    "Eternity308 (Easter Egg 1)": "Eternity308（复活节彩蛋 1）",
    "foxes1338 (Easter Egg 3)": "foxes1338（复活节彩蛋 3）",
    "garnet420 (Easter Egg 1 and 3)": "garnet420（复活节彩蛋 1 和 3）",
    "Infinity 1": "无限 1",
    "Infinity 2": "无限 2",
    "JashinFanatic (Easter Egg 1 and 3)": "JashinFanatic（复活节彩蛋 1 和 3）",
    "luenix (Easter Egg 1 and 2)": "luenix（复活节彩蛋 1 和 2）",
    "Mike95358 (Easter Egg 3)": "Mike95358（复活节彩蛋3）",
    "Negative numbers x 1e80000 but '^' and '-+' have no effect": "负数 x 1e80000 但 '^' 和 '-+' 无效",
    "Next layer at complete Boost or nerf 4.": "完成 提升 或 削弱 4 的下一层。",
    "Rabbit (Easter Egg 3)": "兔子（复活节彩蛋 3）",
    "Reality 1": "现实 1",
    "Reality 2": "现实2",
    "Remove the hardcap of -2 but nerf it.": "移除 -2 的硬上限，但削弱它。",
    "Remove the hardcap of -4 but nerf it and nerf IP gain.": "移除 -4 的硬上限，但削弱它并削弱 IP 增益。",
    "Reset Eternity challenge": "重置永恒挑战",
    "Reset Infinity challenge": "重置无限挑战",
    "Reset Reality challenge": "重置现实挑战",
    "starkirby (Easter Egg 3)": "starkirby（复活节彩蛋 3）",
    "TrueDiego ΔΔΔ (Easter Egg 1 and 4)": "TrueDiego ΔΔΔ（复活节彩蛋 1 和 4）",
    "Unlock 1 Factor Upgrade.": "解锁 1 个因子升级。",
    "Unlock 1 Infinity challenge": "解锁 1 无限挑战",
    "Unlock 1 Infinity point Challenge": "解锁 1 个无限点挑战",
    "Unlock 1 Infinity point challenge.": "解锁 1 个无限点挑战。",
    "Unlock 2 Infinity challenge": "解锁 2 无限挑战",
    "Unlock 2 Infinity point challenge.": "解锁 2 个无限点挑战。",
    "Unlock 2 Infinity point Challenge.": "解锁 2 个无限点挑战。",
    "Exponentiation": "幂运算",
    "Exponentiation points boost X gain": "指数点提升 X 增益",
    "Exponentiation points boost Y gain": "指数点提高 Y 增益",
    "Game speed x10": "游戏速度 x10",
    "Get 100 prestige point on reset.": "重置时获得100声望点。",
    "Get 25 prestige point on reset and unlock 1 upgrade. You can't get any super prestige point": "重置时获得 25 点声望并解锁 1 次升级。 你无法获得任何超级声望点",
    "Auto buy Number upgrade and Factor Upgrade and Number, points x1e20, FS reset nothing and Unlock 1 IC.": "自动购买数字升级和因子升级和数字，点数x1e20，FS重置没有和解锁1个IC。",
    "Auto get Challenge point. CP boost super prestige point gain.": "自动获得挑战点。 CP提升超威望点增益。",
    "Auto get super prestige point.": "自动获得超级声望点。",
    "Boost '9' and '0'": "提升“9”和“0”",
    "Boost game speed based on your Factor.": "根据您的因子提高游戏速度。",
    "Boost game speed based on your IP.": "根据您的 IP 提高游戏速度。",
    "Boost point gain base on exponentiation point and X gain x2.5, Y gain *1.5.": "提升点数增益基于取幂点数和 X 增益 x2.5，Y 增益 *1.5。",
    "Boost X and Y gain based on Prestige points and X, Y gain x2.": "根据声望点和 X、Y 增益 x2 提升 X 和 Y 增益。",
    "IP ^1.1 and unlock 1 IC. Auto buy FS. Number x10.": "IP ^1.1 并解锁 1 个 IC。 自动购买FS。 编号 x10。",
    "IP boost X gain and X boost IP gain.": "IP 提升 X 增益和 X 提升 IP 增益。",
    "Keep F content and I milestones on reset, IP boost point gain.": "在重置时保留 F 内容和 I 里程碑，IP 提升点增益。",
    "Keep IP milestone 4, F milestone 4, 16 and UF milestone 6 and 7 on reset. IP gain ^1.1. Remove the hardcap of NN gain.": "保留 IP 里程碑 4、F 里程碑 4、16 和 UF 里程碑 6 和 7 处于重置状态。 知识产权增益 ^1.1。 移除 NN 增益的硬上限。",
    "MS reset nothing and Buyable is cheaper, gain 100000% of EP on reset per second": "MS什么都不重置，可购买更便宜，每秒重置获得100000％的EP",
    "Remove IP challenge but Number ^25.": "删除 IP 质询但编号 ^25。",
    "Super prestige point boost X and Y gain and Y +1.": "超威望点提升 X 和 Y 增益和 Y +1。",
    "Unlock Hyper prestige and auto get prestige point.": "解锁超威望并自动获得声望点。",
    "Unlock z in Exponentiation. Unlock more Exponentiation and UF Upgrade.": "在求幂中解锁 z。 解锁更多指数和超频升级。",
    "x +1 per second": "x +1 每秒",
    "X boost Y gain.": "X 提升 Y 增益。",
    "X gain ^1.25": "X 增益 ^1.25",
    "y +0.01 per second": "y +0.01 每秒",
    "Y boost X gain": "Y 提升 X 增益",
    "Y gain *2": "Y增益*2",
    "You can't get any prestige point.": "你不能得到任何声望点。",
    "You can't get any super prestige point and remove the hardcap of Exponentiation point gain.": "您无法获得任何超级声望点并取消指数点增益的硬上限。",
    "'x' and '/' cost is higher": "'x' 和 '/' 成本更高",
    "Factor exponent is: 0.314 (Factors are cheaper)": "因子指数为：0.314（因子更便宜）",
    "Numbers gain ^ 3.08": "数字增益 ^ 3.08",
    "unlock '-3'. You can buy this upgrade while you are in Infinity Challenge 3.": "解锁“-3”。 您可以在无限挑战 3 中购买此升级。",
    "Unlock 1 Number Upgrade.": "解锁 1 个数字升级。",
    "Upgrade Upgrader": "升级升级器",
    "Boost '9' and '0' in UF layer and unlock new UF upgrade.": "在 UF 层提升“9”和“0”并解锁新的 UF 升级。",
    "Boost '9' and '10'.": "提升“9”和“10”。",
    "Boost the fifth milestone.": "推进第五个里程碑。",
    "Boost the UF buyable and UF buyable is cheaper based on your EP.": "根据您的 EP，提升 UF 可购买和 UF 可购买更便宜。",
    "Challenge points boost EP gain.": "挑战点可提升 EP 增益。",
    "Clear selector data": "清除选择器数据",
    "EP boost Number gain.": "EP boost 数字增益。",
    "Eternity points": "永恒点",
    "Factor boost Number gain and unlock 2 upgrade.": "因子提升数字增益和解锁 2 升级。",
    "gain 1000% of Ordinal on reset per second.": "每秒重置时获得 1000% 的序数。",
    "Keep IP, I, F and UF milestone, Infinity challenge and Negative numbers challenge on reset. Number ^1.2.": "在重置时保持 IP、I、F 和 UF 里程碑、无限挑战和负数挑战。编号 ^1.2。",
    "Keep NN upgrade and IP challenge on reset.": "重置时保持 NN 升级和 IP 质询。",
    "Keep UF upgrade on reset.": "重置时保持 UF 升级。",
    "Number ^0.5 per click. Currently: ^0.00": "每次点击次数 ^0.5。当前：^0.00",
    "Number ^1.2 if you are in E challenges.": "如果您参加 E 挑战，请编号 ^1.2。",
    "Number ^1.5 if you are not in E challenge, gain 1000% of EP on reset per second": "Number ^1.5 如果你没有在 E 挑战中，每秒重置 1000% 的 EP",
    "Prestige": "声望",
    "Remove the first effect in the eleventh milestone in IP layer. Auto buy Infinity and Infinity reset nothing.": "移除 IP 层第十一个里程碑中的第一个效果。自动购买 无限 和 无限 不会重置任何内容。",
    "Reset Your x and y for 1 Prestige point (Req: 1e150 Exponentiation points).": "将您的 x 和 y 重置为 1 威望点（要求：1e150 指数点）。",
    "Reset Your x, y, prestige point and MS milestone for 1 Super Prestige point (Req: 1e4000 Exponentiation points and 25 prestige point.).": "重置您的 x、y、声望点和 MS 里程碑以获得 1 个超级声望点（要求：1e4000 指数点和 25 个声望点。）。",
    "The first challenge selector is easier based on EP.": "第一个挑战选择器基于 EP 更容易。",
    "Unlock 1 challenge and EP boost Number gain.": "解锁 1 个挑战和 EP 提升数量增益。",
    "Unlock 1 Mathematician challenge.": "解锁 1 个数学家挑战。",
    "Unlock 1 NN chalenge.": "解锁 1 个 NN 挑战。",
    "Unlock 2 layer.": "解锁 2 层。",
    "Unlock 5 EP upgrade but you only can buy Challenge points^0.5 upgrade.": "解锁 5 EP 升级，但您只能购买挑战点^0.5 升级。",
    "Unlock galaxy. You can buy Max Mathematics Symbol": "解锁银河。您可以购买最大数学符号",
    "Unlock more challenge selector.": "解锁更多挑战选择器。",
    "You can buy max factor.": "您可以购买最大因子。",
    "You can complete challenge without in Boost or Nerf 4.": "您可以在没有 提升 或 削弱 4 的情况下完成挑战。",
    "You can do reset without in Boost or Nerf 4 (Exclude challenge).": "您可以在没有 提升 或 削弱 4（排除挑战）的情况下进行重置。",
    "You can get more EP, factor are cheaper.": "你可以获得更多的EP，因子更便宜。",
    "You can reset while you are in Boost or nerf 4.": "您可以在 提升 或 削弱 4 中重置。",
    "Unlock 1 layer": "解锁 1 个层",
    "point gain ^2 and remove the hardcap of IP gain but nerf IP gain.": "点数增益 ^2 并移除 IP 增益的硬上限，但会削弱 IP 增益。",
    "1 effect is better": "1效果更好",
    "Antimatter Dimensions player777 (Easter Egg 3)": "反物质维度 player777（复活节彩蛋 3）",
    "bananenkeks (Easter Egg 4)": "香蕉（复活节彩蛋 4）",
    "Boost '3'": "提升'3'",
    "Factor alpha": "系数α",
    "Factor alpha effect is better": "因子α效应更好",
    "Factor beta": "因子β",
    "Factor beta effect is better": "β因子效果更好",
    "Factor Epsilon effect is better": "因子 Epsilon 效果更好",
    "Factor Gamma effect is better": "因子 Gamma 效果更好",
    "FS boost point gain but Factor, Upgrade factor are more expensive.": "FS 提升点增益但因子、升级因子更昂贵。",
    "Negative 2, 3, 4": "负 2、3、4",
    "Negative buyable": "负可买",
    "Negative cheaper": "负便宜",
    "Negative numbers Boost Number gain.": "负数 Boost Number 增益。",
    "Negative UFC": "负UFC",
    "Negative upgrade factor": "负升级因子",
    "Number": "数字",
    "Number ^1.5 and unlock 1 feature in UF layer.": "编号 ^1.5 并解锁 UF 层中的 1 个功能。",
    "Number ^2": "数字 ^2",
    "Number ^2 but '2', '3', '4', '-2', '-3' and '-4' is disabled and nerf factor beta.": "数字 ^2 但 '2'、'3'、'4'、'-2'、'-3' 和 '-4' 被禁用并且 削弱 因子 beta。",
    "Number ^2 but FC, UFC effect are disabled and nerf factor beta.": "编号 ^2 但 FC、UFC 效果被禁用并且 削弱 因子 beta。",
    "Number ^8 but Row 1 to Row 2 buyable are disabled and nerf factor beta.": "编号 ^8，但第 1 行到第 2 行可购买已禁用且 削弱 因子 beta。",
    "Number boost themselves.": "号自增。",
    "Number gain ^0.012 and Row 1 to Row 2 buyable are disabled": "数字增益 ^0.012 和第 1 行到第 2 行可购买被禁用",
    "Number gain ^0.023 and Factor, Upgrade factor are more expensive.": "数字增益 ^0.023 和因子，升级因子更昂贵。",
    "Number gain ^0.034 and Remove UF layer.": "数字增益 ^0.034 并移除 UF 层。",
    "Number gain ^0.123 and FC, UFC effect are disabled (You need to reload to complete FC after exit it.)": "数字增益^0.123，FC、UFC效果关闭（退出后需要重新加载完成FC。）",
    "Number gain ^0.234 and '2', '3', '4', '-2', '-3' and '-4' is disabled": "数字增益 ^0.234 和 '2'、'3'、'4'、'-2'、'-3' 和 '-4' 被禁用",
    "Point boost number gain.": "点提升数字增益。",
    "Point boost point gain.": "点提升点增益。",
    "Point boost themselves.": "点boost自己。",
    "Raise point gain to 4.": "将积分增益提高到 4。",
    "Remove some useless upgrade and IP ^2.": "删除一些无用的升级和IP ^2。",
    "Unlock 1 Infinity challenge.": "解锁 1 个无限挑战。",
    "Unlock 1 NN challenge.": "解锁 1 个 NN 挑战。",
    "Unlock 3 Number upgrades.": "解锁 3 个数字升级。",
    "Upgrade power": "升级电源",
    "You are gaining e6.702e10 Infinity point per second": "您每秒获得 e6.702e10 无限点",
    "You can finish Boost or nerf after get e9e15 Number.": "获得 e9e15 数字后，您可以完成 提升 或 削弱",
    "You can get more then 2 Super prestige point.": "您可以获得超过 2 个超级声望点。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'QQ群号:': 'QQ群号:',
    'N': 'N',
    'F': 'F',
    'I': 'I',
    'UF': 'UF',
    'i': 'i',
    'G': 'G',
    'x': 'x',
    'L': 'L',
    'O': 'O',
    'M': 'M',
    'T': 'T',
    'X': 'X',
    'v0.3.2.1 alpha 1': 'v0.3.2.1 alpha 1',
    'OM': 'OM',
    'FS': 'FS',
    'MS': 'MS',
    'S': 'S',
    '+': '+',
    '-': '-',
    'A': 'A',
    'IP': 'IP',
    'NN': 'NN',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Time played (real time): ": "游戏时长（实时）：",
    "Numbers and points gain x": "数字和点数增益 x",
    "Numbers and Points x": "数字和点数 x",
    "Boosts Numbers gain by ": "提升 数字 增益 ",
    "Boosts numbers gain by ": "提升 数字 增益 ",
    "Boosts Negative numbers gain by ": "提升 负数 增益 ",
    "Boosts points gain by ": "提升 点数 增益 ",
    "NN gain ^": "NN 增益 ^",
    "Number gain x": "数字增益 x",
    "IP gain ^": "IP 增益 ^",
    "Negative numbers ^": "负数 ^",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x\^y \= ([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)x$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Your x is (.+)$/, '你的 x 是 $1'],
    [/^Your y is (.+)$/, '你的 x 是 $1'],
    [/^Number \^(.+) but nerf factor beta.$/, '数字 \^$1 但 削弱 因子 beta。'],
    [/^You Will get (.+) Challenge points.$/, '您将获得 $1 挑战点数。'],
    [/^Next at (.+) Infinity$/, '下一个在 $1 无限'],
    [/^EP gain \^([\d\.]+).$/, 'EP \^$1.'],
    [/^Number gain \^([\d\.]+).$/, '数字增益 \^$1.'],
    [/^Number gain \^\((.+)\/(.+)\).$/, '数字增益 \^\($1\/$2\).'],
    [/^Number gain \^([\d\.]+) .$/, '数字增益 \^$1.'],
    [/^Numbers gain \^([\d\.]+).$/, '数字增益 \^$1.'],
    [/^Next layer at (.+) Infinity.$/, '下一层在 $1 无限。'],
    [/^Next layer at (.+) Factor challenge$/, '下一层在 $1 因子挑战'],
    [/^(.+) Negative numbers \((.+) Negative numbers after complete Eternity (.+)\)$/, '$1 负数（完成 永恒 $3 后的 $2 负数）'],
    [/^(.+) Negative numbers \((.+) Negative numbers after complete Reality (.+)\)$/, '$1 负数（完成 现实 $3 后的 $2 负数）'],
    [/^(.+) Negative numbers \((.+) Negative numbers after complete Infinity (.+)\)$/, '$1 负数（完成 无限 $3 后的 $2 负数）'],
    [/^You have (.+) Exponentiation points.$/, '您有 $1 幂运算点数。'],
    [/^You have (.+) Challenge points. \(Based on best\)$/, '您有 $1 挑战点。 （基于最佳）'],
    [/^Your have (.+) prestige point$/, '您有 $1 声望点'],
    [/^Your have (.+) super prestige point$/, '您有 $1 超级声望点'],
    [/^You have (.+) Factors$/, '您有 $1 因子'],
    [/^You have (.+) layers left to unlock.$/, '您还有 $1 层需要解锁。'],
    [/^You have completed this challenge (.+) times.$/, '您已完成此挑战 $1 次。'],
    [/^You are gaining (.+) Factor Point per second.$/, '您每秒获得 $1 因子点数。'],
    [/^You are gaining (.+) Numbers per second$/, '您每秒获得 $1 数字'],
    [/^You are gaining (.+) Negative numbers per second$/, '您每秒获得 $1 负数'],
    [/^(.+) base x(.+). You can buy this upgrade while you are in Factor Challenge (.+).$/, '$1 基数 x$2。 您可以在因子挑战 $3 中购买此升级。'],
    [/^You have (.+) Factor point, which make factor cost base (.+)$/, '您有 $1 因子点数，这使得因子成本基数 $2'],
    [/^Your have (.+) prime factor point, which boost factor and number exp by (.+).$/, '您有 $1 素数因子点数，这会将因数和数字 指数 提高 $2。'],
    [/^You have (.+) Negative numbers$/, '你有 $1 负数'],
    [/^You have (.+) Negative Numbers$/, '你有 $1 负数'],
    [/^You have (.+) Numbers$/, '你有 $1 数字'],
    [/^You have (.+) Infinity$/, '你有 $1 无限'],
    [/^Get (.+) Number upgrade$/, '获得 $1 个数字升级'],
    [/^Get (.+) Number upgrade.$/, '获得 $1 个数字升级。'],
    [/^Get (.+) upgrade.$/, '获得 $1 升级。'],
    [/^Get (.+) factor$/, '获得 $1 因子'],
    [/^Get (.+) factor.$/, '获得 $1 因子。'],
    [/^Get (.+) factors.$/, '获得 $1 因子。'],
    [/^Get (.+) factors$/, '获得 $1 因子'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) Infinity$/, '$1e$2 无限'],
    [/^([\d\.]+)e([\d\.,]+) Numbers$/, '$1e$2 数字'],
    [/^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+) Numbers$/, '$1e$2 \/ $3e$4 数字'],
    [/^([\d\.]+)e([\d\.,]+) Points$/, '$1e$2 点数'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)e([\d\.,]+) Upgrade Factor$/, '$1e$2 升级因子'],
    [/^([\d\.]+)e([\d\.,]+) Negative number$/, '$1e$2 负数'],
    [/^([\d\.]+)e([\d\.,]+) Eternity points$/, '$1e$2 永恒点'],
    [/^([\d\.]+)e([\d\.,]+) Factors$/, '$1e$2 因子'],
    [/^([\d\.]+)e([\d\.,]+) numbers$/, '$1e$2 数字'],
    [/^([\d\.]+)e([\d\.,]+) point$/, '$1e$2 点数'],
    [/^([\d\.]+)e([\d\.,]+) factors$/, '$1e$2 因子'],
    [/^([\d\.]+)e([\d\.,]+) Ordinal$/, '$1e$2 序数'],
    [/^([\d\.]+)e([\d\.,]+) Negative numbers$/, '$1e$2 负数'],
    [/^e([\d\.,]+) Negative numbers$/, 'e$1 负数'],
    [/^e([\d\.]+)e([\d\.,]+) IP$/, 'e$1e$2 IP'],
    [/^e([\d\.]+)e([\d\.,]+) Negative numbers$/, 'e$1e$2 负数'],
    [/^([\d\.]+)e([\d\.,]+) Infinity point$/, '$1e$2 无限点'],
    [/^([\d\.]+)e([\d\.,]+) Infinity points$/, '$1e$2 无限点'],
    [/^e([\d\.]+)e([\d\.,]+) Infinity point$/, 'e$1e$2 无限点'],
    [/^e([\d\.]+)e([\d\.,]+) Infinity points$/, 'e$1e$2 无限点'],
    [/^([\d\.]+)e([\d\.,]+) Numbers$/, '$1e$2 数字'],
    [/^e([\d\.,]+) Numbers$/, 'e$1 数字'],
    [/^e([\d\.]+)e([\d\.,]+) Numbers$/, 'e$1e$2 数字'],
    [/^e([\d\.]+)e([\d\.,]+) Numbers$/, 'e$1e$2 数字'],
    [/^([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+) Numbers$/, '$1 \/ $2e$3 数字'],
    [/^e([\d\.,]+) \/ e([\d\.,]+) Numbers$/, 'e$1 \/ e$2 数字'],
    [/^e([\d\.]+)e([\d\.,]+) \/ e([\d\.]+)e([\d\.,]+) Numbers$/, 'e$1e$2 \/ e$3e$4 数字'],
    [/^Number \^([\d\.]+) but NN \^([\d\.]+).$/, '数字 \^$1 但 NN \^$2。'],
    [/^Number \^([\d\.]+).$/, '数字 \^$1。'],
    [/^Numbers \^([\d\.]+).$/, '数字 \^$1。'],
    [/^Number gain \^([\d\.]+)$/, '数字增益 \^$1'],
    [/^Number gain \^([\d\.]+).$/, '数字增益 \^$1。'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) in ([\d\.,]+)$/, '$1 合 $2'],
    [/^Boost or nerf ([\d\.,]+)$/, '提升或削弱 $1'],
    [/^Boost \'([\d\.,]+)\'.$/, '提升 \'$1\'.'],
    [/^([\d\.,]+) prestige point$/, '$1 声望点'],
    [/^([\d\.,]+) Mathematics Symbol with F6.1 Upgrade$/, '$1 数学符号与F6.1升级'],
    [/^([\d\.,]+) Hyper prestige point$/, '$1 究级声望点'],
    [/^([\d\.,]+) Super prestige point.$/, '$1 超级声望点。'],
    [/^([\d\.,]+) Factor shift$/, '$1 因子偏移'],
    [/^([\d\.,]+) Mathematics Symbol$/, '$1 数学符号'],
    [/^([\d\.,]+) Challenge points$/, '$1 挑战点'],
    [/^([\d\.,]+) Eternity points$/, '$1 永恒点'],
    [/^([\d\.,]+) Ordinal$/, '$1 序数'],
    [/^([\d\.,]+) Infinity point$/, '$1 无限点'],
    [/^([\d\.,]+) Infinity points$/, '$1 无限点'],
    [/^([\d\.,]+) Negative numbers$/, '$1 负数'],
    [/^([\d\.,]+) Negative Numbers$/, '$1 负数'],
    [/^([\d\.,]+) Numbers$/, '$1 数字'],
    [/^([\d\.,]+) points$/, '$1 点数'],
    [/^([\d\.,]+) Infinity$/, '$1 无限'],
    [/^([\d\.,]+) Upgrade Factor$/, '$1 升级因子'],
    [/^([\d\.,]+) factor$/, '$1 因子'],
    [/^([\d\.,]+) factors$/, '$1 因子'],
    [/^([\d\.,]+) Factors$/, '$1 因子'],
    [/^\((.+)\/sec\)$/, '（$1\/秒）'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) Factors$/, '成本：$1 因子'],
    [/^Cost: Infinity Numbers$/, '成本：无限 数字'],
    [/^Cost : Infinity Numbers$/, '成本：无限 数字'],
    [/^Cost: Infinity Negative numbers$/, '成本：无限  负数'],
    [/^Cost: (.+) Negative numbers$/, '成本：$1 负数'],
    [/^Cost: (.+) Infinity point$/, '成本：$1 无限点'],
    [/^Cost: (.+) Numbers$/, '成本：$1 数字'],
    [/^Cost : (.+) Factors$/, '成本：$1 因子'],
    [/^Cost : (.+) Numbers$/, '成本：$1 数字'],
    [/^Cost : (.+) Negative numbers$/, '成本：$1 负数'],
    [/^Cost: (.+) Exponentiation points$/, '成本：$1 幂运算点数'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Currently: (.+)x$/, '当前：$1x'],
    [/^Req: (.+) \/ (.+) Number$/, '要求：$1 \/ $2 数字'],
    [/^Req: (.+) \/ (.+) Numbers$/, '要求：$1 \/ $2 数字'],
    [/^Req: (.+) \/ (.+) Infinity point$/, '要求：$1 \/ $2 无限点'],
    [/^Req: (.+) \/ (.+) Eternity points$/, '要求：$1 \/ $2 永恒点'],
    [/^Req: (.+) \/ (.+) Factors$/, '要求：$1 \/ $2 因子'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);